package dto.vistaTablas;
// Generated 11/12/2015 11:59:28 AM by Hibernate Tools 4.3.1

import java.io.Serializable;

/**
 * Credito generated by hbm2java
 */
public class CreditoTablas implements Serializable {

  // VARIABLES DE CLASE
  private String numeroCredito;
  private Float monto;
  private String institucion;
  private String razonSocialDeudor;
  private String gestorAsignado;

  // CONSTRUCTOR
  public CreditoTablas() {
  }
  
  // GETTERS & SETTERS
  public String getNumeroCredito() {
    return numeroCredito;
  }

  public void setNumeroCredito(String numeroCredito) {
    this.numeroCredito = numeroCredito;
  }

  public Float getMonto() {
    return monto;
  }

  public void setMonto(Float monto) {
    this.monto = monto;
  }

  public String getRazonSocialDeudor() {
    return razonSocialDeudor;
  }

  public void setRazonSocialDeudor(String razonSocialDeudor) {
    this.razonSocialDeudor = razonSocialDeudor;
  }

  public String getGestorAsignado() {
    return gestorAsignado;
  }

  public void setGestorAsignado(String gestorAsignado) {
    this.gestorAsignado = gestorAsignado;
  }

  public String getInstitucion() {
    return institucion;
  }

  public void setInstitucion(String institucion) {
    this.institucion = institucion;
  }
  
}
