package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Administrativos generated by hbm2java
 */
public class Administrativos  implements java.io.Serializable {


     private Integer idAdministrativo;
     private Usuarios usuarios;

    public Administrativos() {
    }

    public Administrativos(Usuarios usuarios) {
       this.usuarios = usuarios;
    }
   
    public Integer getIdAdministrativo() {
        return this.idAdministrativo;
    }
    
    public void setIdAdministrativo(Integer idAdministrativo) {
        this.idAdministrativo = idAdministrativo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


