package dto;
// Generated 9/02/2016 02:44:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AsuntoGestion generated by hbm2java
 */
public class AsuntoGestion  implements java.io.Serializable {


     private Integer idAsuntoGestion;
     private TipoAsuntoGestion tipoAsuntoGestion;
     private TipoGestion tipoGestion;
     private Set gestions = new HashSet(0);
     private Set descripcionGestions = new HashSet(0);

    public AsuntoGestion() {
    }

	
    public AsuntoGestion(TipoAsuntoGestion tipoAsuntoGestion, TipoGestion tipoGestion) {
        this.tipoAsuntoGestion = tipoAsuntoGestion;
        this.tipoGestion = tipoGestion;
    }
    public AsuntoGestion(TipoAsuntoGestion tipoAsuntoGestion, TipoGestion tipoGestion, Set gestions, Set descripcionGestions) {
       this.tipoAsuntoGestion = tipoAsuntoGestion;
       this.tipoGestion = tipoGestion;
       this.gestions = gestions;
       this.descripcionGestions = descripcionGestions;
    }
   
    public Integer getIdAsuntoGestion() {
        return this.idAsuntoGestion;
    }
    
    public void setIdAsuntoGestion(Integer idAsuntoGestion) {
        this.idAsuntoGestion = idAsuntoGestion;
    }
    public TipoAsuntoGestion getTipoAsuntoGestion() {
        return this.tipoAsuntoGestion;
    }
    
    public void setTipoAsuntoGestion(TipoAsuntoGestion tipoAsuntoGestion) {
        this.tipoAsuntoGestion = tipoAsuntoGestion;
    }
    public TipoGestion getTipoGestion() {
        return this.tipoGestion;
    }
    
    public void setTipoGestion(TipoGestion tipoGestion) {
        this.tipoGestion = tipoGestion;
    }
    public Set getGestions() {
        return this.gestions;
    }
    
    public void setGestions(Set gestions) {
        this.gestions = gestions;
    }
    public Set getDescripcionGestions() {
        return this.descripcionGestions;
    }
    
    public void setDescripcionGestions(Set descripcionGestions) {
        this.descripcionGestions = descripcionGestions;
    }




}


