package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

/**
 * La clase {@code Auto} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Auto implements java.io.Serializable {

    private int idAuto;
    private Credito credito;
    private String clave;
    private String marca;
    private String modelo;
    private String color;
    private Float valor;

    /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Auto() {
    }

    /**
     * Constructor parametrizado. <br/>
     * Configura ...
     */
    public Auto(int idAuto, Credito credito) {
        this.idAuto = idAuto;
        this.credito = credito;
    }

    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public Auto(int idAuto, Credito credito, String clave, String marca, String modelo, String color, Float valor) {
        this.idAuto = idAuto;
        this.credito = credito;
        this.clave = clave;
        this.marca = marca;
        this.modelo = modelo;
        this.color = color;
        this.valor = valor;
    }

    /**
     *
     *
     * @return
     */
    public int getIdAuto() {
        return this.idAuto;
    }

    /**
     *
     *
     * @param
     */
    public void setIdAuto(int idAuto) {
        this.idAuto = idAuto;
    }

    /**
     *
     *
     * @return
     */
    public Credito getCredito() {
        return this.credito;
    }

    /**
     *
     *
     * @param
     */
    public void setCredito(Credito credito) {
        this.credito = credito;
    }

    /**
     *
     *
     * @return
     */
    public String getClave() {
        return this.clave;
    }

    /**
     *
     *
     * @param
     */
    public void setClave(String clave) {
        this.clave = clave;
    }

    /**
     *
     *
     * @return
     */
    public String getMarca() {
        return this.marca;
    }

    /**
     *
     *
     * @param
     */
    public void setMarca(String marca) {
        this.marca = marca;
    }

    /**
     *
     *
     * @return
     */
    public String getModelo() {
        return this.modelo;
    }

    /**
     *
     *
     * @param
     */
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    /**
     *
     *
     * @return
     */
    public String getColor() {
        return this.color;
    }

    /**
     *
     *
     * @param
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     *
     *
     * @return
     */
    public Float getValor() {
        return this.valor;
    }

    /**
     *
     *
     * @param valor
     */
    public void setValor(Float valor) {
        this.valor = valor;
    }
}