package dto;
// Generated 15/06/2015 12:32:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Autos generated by hbm2java
 */
@Entity
@Table(name="autos"
    ,catalog="sigerbd"
)
public class Autos  implements java.io.Serializable {


     private int idAuto;
     private Creditos creditos;
     private String clave;
     private String marca;
     private String modelo;
     private String color;
     private Float valor;

    public Autos() {
    }

	
    public Autos(int idAuto, Creditos creditos) {
        this.idAuto = idAuto;
        this.creditos = creditos;
    }
    public Autos(int idAuto, Creditos creditos, String clave, String marca, String modelo, String color, Float valor) {
       this.idAuto = idAuto;
       this.creditos = creditos;
       this.clave = clave;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.valor = valor;
    }
   
     @Id 

    
    @Column(name="id_auto", unique=true, nullable=false)
    public int getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(int idAuto) {
        this.idAuto = idAuto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creditos_id_credito", nullable=false)
    public Creditos getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Creditos creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="clave", length=30)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="marca", length=25)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="modelo", length=25)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="color", length=25)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="valor", precision=12, scale=0)
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }




}


