package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Autos generated by hbm2java
 */
public class Autos  implements java.io.Serializable {


     private int idAuto;
     private Creditos creditos;
     private String clave;
     private String marca;
     private String modelo;
     private String color;
     private Float valor;

    public Autos() {
    }

	
    public Autos(int idAuto, Creditos creditos) {
        this.idAuto = idAuto;
        this.creditos = creditos;
    }
    public Autos(int idAuto, Creditos creditos, String clave, String marca, String modelo, String color, Float valor) {
       this.idAuto = idAuto;
       this.creditos = creditos;
       this.clave = clave;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.valor = valor;
    }
   
    public int getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(int idAuto) {
        this.idAuto = idAuto;
    }
    public Creditos getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Creditos creditos) {
        this.creditos = creditos;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }




}


