package dto;
// Generated 20/10/2016 11:15:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BloqueVisita generated by hbm2java
 */
public class BloqueVisita  implements java.io.Serializable {


     private Integer idBloque;
     private Gestor gestor;
     private Date fechaAutorizacion;
     private Date fechaAsignada;
     private Set detalleVisitas = new HashSet(0);

    public BloqueVisita() {
    }

	
    public BloqueVisita(Gestor gestor, Date fechaAutorizacion, Date fechaAsignada) {
        this.gestor = gestor;
        this.fechaAutorizacion = fechaAutorizacion;
        this.fechaAsignada = fechaAsignada;
    }
    public BloqueVisita(Gestor gestor, Date fechaAutorizacion, Date fechaAsignada, Set detalleVisitas) {
       this.gestor = gestor;
       this.fechaAutorizacion = fechaAutorizacion;
       this.fechaAsignada = fechaAsignada;
       this.detalleVisitas = detalleVisitas;
    }
   
    public Integer getIdBloque() {
        return this.idBloque;
    }
    
    public void setIdBloque(Integer idBloque) {
        this.idBloque = idBloque;
    }
    public Gestor getGestor() {
        return this.gestor;
    }
    
    public void setGestor(Gestor gestor) {
        this.gestor = gestor;
    }
    public Date getFechaAutorizacion() {
        return this.fechaAutorizacion;
    }
    
    public void setFechaAutorizacion(Date fechaAutorizacion) {
        this.fechaAutorizacion = fechaAutorizacion;
    }
    public Date getFechaAsignada() {
        return this.fechaAsignada;
    }
    
    public void setFechaAsignada(Date fechaAsignada) {
        this.fechaAsignada = fechaAsignada;
    }
    public Set getDetalleVisitas() {
        return this.detalleVisitas;
    }
    
    public void setDetalleVisitas(Set detalleVisitas) {
        this.detalleVisitas = detalleVisitas;
    }




}


