package dto;
// Generated 22/02/2016 10:19:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Campana generated by hbm2java
 */
public class Campana  implements java.io.Serializable {


     private Integer idCampana;
     private String nombre;
     private String descripcion;
     private Set creditos = new HashSet(0);

    public Campana() {
    }

	
    public Campana(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Campana(String nombre, String descripcion, Set creditos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.creditos = creditos;
    }
   
    public Integer getIdCampana() {
        return this.idCampana;
    }
    
    public void setIdCampana(Integer idCampana) {
        this.idCampana = idCampana;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }




}


