package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idCliente;
     private Sujetos sujetos;
     private String numeroCliente;
     private String curp;
     private String numeroSeguroSocial;
     private Set creditoses = new HashSet(0);
     private Set contactoses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public Clientes(Sujetos sujetos, String numeroCliente, String curp, String numeroSeguroSocial, Set creditoses, Set contactoses) {
       this.sujetos = sujetos;
       this.numeroCliente = numeroCliente;
       this.curp = curp;
       this.numeroSeguroSocial = numeroSeguroSocial;
       this.creditoses = creditoses;
       this.contactoses = contactoses;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public String getNumeroCliente() {
        return this.numeroCliente;
    }
    
    public void setNumeroCliente(String numeroCliente) {
        this.numeroCliente = numeroCliente;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getNumeroSeguroSocial() {
        return this.numeroSeguroSocial;
    }
    
    public void setNumeroSeguroSocial(String numeroSeguroSocial) {
        this.numeroSeguroSocial = numeroSeguroSocial;
    }
    public Set getCreditoses() {
        return this.creditoses;
    }
    
    public void setCreditoses(Set creditoses) {
        this.creditoses = creditoses;
    }
    public Set getContactoses() {
        return this.contactoses;
    }
    
    public void setContactoses(Set contactoses) {
        this.contactoses = contactoses;
    }




}


