package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * La clase {@code Cliente} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Cliente implements java.io.Serializable {

    private Integer idCliente;
    private Sujeto sujeto;
    private String numeroCliente;
    private String curp;
    private String numeroSeguroSocial;
    private Set creditos = new HashSet(0);
    private Set contactos = new HashSet(0);

    /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Cliente() {
    }

    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public Cliente(Sujeto sujeto) {
        this.sujeto = sujeto;
    }

    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public Cliente(Sujeto sujeto, String numeroCliente, String curp, String numeroSeguroSocial, Set creditos, Set contactos) {
        this.sujeto = sujeto;
        this.numeroCliente = numeroCliente;
        this.curp = curp;
        this.numeroSeguroSocial = numeroSeguroSocial;
        this.creditos = creditos;
        this.contactos = contactos;
    }

    /**
     *
     *
     * @return
     */
    public Integer getIdCliente() {
        return this.idCliente;
    }

    /**
     *
     *
     * @param
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     *
     *
     * @return
     */
    public Sujeto getSujeto() {
        return this.sujeto;
    }

    /**
     *
     *
     * @param
     */
    public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }

    /**
     *
     *
     * @return
     */
    public String getNumeroCliente() {
        return this.numeroCliente;
    }

    /**
     *
     *
     * @param
     */
    public void setNumeroCliente(String numeroCliente) {
        this.numeroCliente = numeroCliente;
    }

    /**
     *
     *
     * @return
     */
    public String getCurp() {
        return this.curp;
    }

    /**
     *
     *
     * @param
     */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /**
     *
     *
     * @return
     */
    public String getNumeroSeguroSocial() {
        return this.numeroSeguroSocial;
    }

    /**
     *
     *
     * @param
     */
    public void setNumeroSeguroSocial(String numeroSeguroSocial) {
        this.numeroSeguroSocial = numeroSeguroSocial;
    }

    public Set getCreditos() {
        return this.creditos;
    }

    /**
     *
     *
     * @param
     */
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }

    /**
     *
     *
     * @return
     */
    public Set getContactos() {
        return this.contactos;
    }

    /**
     *
     *
     * @param
     */
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }
}