package dto;
// Generated 18/08/2015 11:07:25 AM by Hibernate Tools 4.3.1



/**
 * Colonia generated by hbm2java
 */
public class Colonia  implements java.io.Serializable {


     private Integer idColonia;
     private int idMunicipioMunicipios;
     private String tipo;
     private String nombre;
     private String codigoPostal;

    public Colonia() {
    }

	
    public Colonia(int idMunicipioMunicipios, String nombre, String codigoPostal) {
        this.idMunicipioMunicipios = idMunicipioMunicipios;
        this.nombre = nombre;
        this.codigoPostal = codigoPostal;
    }
    public Colonia(int idMunicipioMunicipios, String tipo, String nombre, String codigoPostal) {
       this.idMunicipioMunicipios = idMunicipioMunicipios;
       this.tipo = tipo;
       this.nombre = nombre;
       this.codigoPostal = codigoPostal;
    }
   
    public Integer getIdColonia() {
        return this.idColonia;
    }
    
    public void setIdColonia(Integer idColonia) {
        this.idColonia = idColonia;
    }
    public int getIdMunicipioMunicipios() {
        return this.idMunicipioMunicipios;
    }
    
    public void setIdMunicipioMunicipios(int idMunicipioMunicipios) {
        this.idMunicipioMunicipios = idMunicipioMunicipios;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }




}


