package dto;
// Generated 15/06/2016 09:53:16 AM by Hibernate Tools 4.3.1



/**
 * ComprobantePago generated by hbm2java
 */
public class ComprobantePago  implements java.io.Serializable {


     private Integer idComprobante;
     private Pago pago;
     private String nombreComprobante;

    public ComprobantePago() {
    }

    public ComprobantePago(Pago pago, String nombreComprobante) {
       this.pago = pago;
       this.nombreComprobante = nombreComprobante;
    }
   
    public Integer getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(Integer idComprobante) {
        this.idComprobante = idComprobante;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public String getNombreComprobante() {
        return this.nombreComprobante;
    }
    
    public void setNombreComprobante(String nombreComprobante) {
        this.nombreComprobante = nombreComprobante;
    }




}


