package dto;
// Generated 19/11/2015 10:18:31 AM by Hibernate Tools 4.3.1



/**
 * ConceptoDevolucion generated by hbm2java
 */
public class ConceptoDevolucion  implements java.io.Serializable {


     private Integer idConceptoDevolucion;
     private String concepto;

    public ConceptoDevolucion() {
    }

    public ConceptoDevolucion(String concepto) {
       this.concepto = concepto;
    }
   
    public Integer getIdConceptoDevolucion() {
        return this.idConceptoDevolucion;
    }
    
    public void setIdConceptoDevolucion(Integer idConceptoDevolucion) {
        this.idConceptoDevolucion = idConceptoDevolucion;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }




}


