package dto;
// Generated 15/06/2015 12:32:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contactos generated by hbm2java
 */
@Entity
@Table(name="contactos"
    ,catalog="sigerbd"
)
public class Contactos  implements java.io.Serializable {


     private int idContacto;
     private Clientes clientes;
     private Sujetos sujetos;
     private String observaciones;

    public Contactos() {
    }

	
    public Contactos(int idContacto, Clientes clientes, Sujetos sujetos) {
        this.idContacto = idContacto;
        this.clientes = clientes;
        this.sujetos = sujetos;
    }
    public Contactos(int idContacto, Clientes clientes, Sujetos sujetos, String observaciones) {
       this.idContacto = idContacto;
       this.clientes = clientes;
       this.sujetos = sujetos;
       this.observaciones = observaciones;
    }
   
     @Id 

    
    @Column(name="id_contacto", unique=true, nullable=false)
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clientes_id_cliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sujetos_id_sujeto", nullable=false)
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }

    
    @Column(name="observaciones", length=45)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


