package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Contactos generated by hbm2java
 */
public class Contactos  implements java.io.Serializable {


     private int idContacto;
     private Clientes clientes;
     private Sujetos sujetos;
     private String observaciones;

    public Contactos() {
    }

	
    public Contactos(int idContacto, Clientes clientes, Sujetos sujetos) {
        this.idContacto = idContacto;
        this.clientes = clientes;
        this.sujetos = sujetos;
    }
    public Contactos(int idContacto, Clientes clientes, Sujetos sujetos, String observaciones) {
       this.idContacto = idContacto;
       this.clientes = clientes;
       this.sujetos = sujetos;
       this.observaciones = observaciones;
    }
   
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


