package dto;
// Generated 11/05/2016 10:38:30 AM by Hibernate Tools 4.3.1



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int idContacto;
     private Deudor deudor;
     private Sujeto sujeto;
     private String nombre;
     private String tipo;
     private String observaciones;

    public Contacto() {
    }

	
    public Contacto(int idContacto, Deudor deudor, Sujeto sujeto, String nombre, String tipo) {
        this.idContacto = idContacto;
        this.deudor = deudor;
        this.sujeto = sujeto;
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Contacto(int idContacto, Deudor deudor, Sujeto sujeto, String nombre, String tipo, String observaciones) {
       this.idContacto = idContacto;
       this.deudor = deudor;
       this.sujeto = sujeto;
       this.nombre = nombre;
       this.tipo = tipo;
       this.observaciones = observaciones;
    }
   
    public int getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(int idContacto) {
        this.idContacto = idContacto;
    }
    public Deudor getDeudor() {
        return this.deudor;
    }
    
    public void setDeudor(Deudor deudor) {
        this.deudor = deudor;
    }
    public Sujeto getSujeto() {
        return this.sujeto;
    }
    
    public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


