package dto;
// Generated 27/04/2016 09:32:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConvenioPago generated by hbm2java
 */
public class ConvenioPago  implements java.io.Serializable {


     private Integer idConvenioPago;
     private Credito credito;
     private Date fecha;
     private int estatus;
     private float saldoNegociado;
     private int pagosNegociados;
     private Set promesaPagos = new HashSet(0);

    public ConvenioPago() {
    }

	
    public ConvenioPago(Credito credito, Date fecha, int estatus, float saldoNegociado, int pagosNegociados) {
        this.credito = credito;
        this.fecha = fecha;
        this.estatus = estatus;
        this.saldoNegociado = saldoNegociado;
        this.pagosNegociados = pagosNegociados;
    }
    public ConvenioPago(Credito credito, Date fecha, int estatus, float saldoNegociado, int pagosNegociados, Set promesaPagos) {
       this.credito = credito;
       this.fecha = fecha;
       this.estatus = estatus;
       this.saldoNegociado = saldoNegociado;
       this.pagosNegociados = pagosNegociados;
       this.promesaPagos = promesaPagos;
    }
   
    public Integer getIdConvenioPago() {
        return this.idConvenioPago;
    }
    
    public void setIdConvenioPago(Integer idConvenioPago) {
        this.idConvenioPago = idConvenioPago;
    }
    public Credito getCredito() {
        return this.credito;
    }
    
    public void setCredito(Credito credito) {
        this.credito = credito;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }
    public float getSaldoNegociado() {
        return this.saldoNegociado;
    }
    
    public void setSaldoNegociado(float saldoNegociado) {
        this.saldoNegociado = saldoNegociado;
    }
    public int getPagosNegociados() {
        return this.pagosNegociados;
    }
    
    public void setPagosNegociados(int pagosNegociados) {
        this.pagosNegociados = pagosNegociados;
    }
    public Set getPromesaPagos() {
        return this.promesaPagos;
    }
    
    public void setPromesaPagos(Set promesaPagos) {
        this.promesaPagos = promesaPagos;
    }




}


