package dto;
// Generated 7/08/2015 09:51:09 AM by Hibernate Tools 4.3.1



/**
 * CreditoRemesaId generated by hbm2java
 */
public class CreditoRemesaId  implements java.io.Serializable {


     private int remesasIdRemesa;
     private int creditosIdCredito;

  /**
   *
   */
  public CreditoRemesaId() {
    }

  /**
   *
   * @param remesasIdRemesa
   * @param creditosIdCredito
   */
  public CreditoRemesaId(int remesasIdRemesa, int creditosIdCredito) {
       this.remesasIdRemesa = remesasIdRemesa;
       this.creditosIdCredito = creditosIdCredito;
    }
   
  /**
   *
   * @return
   */
  public int getRemesasIdRemesa() {
        return this.remesasIdRemesa;
    }
    
  /**
   *
   * @param remesasIdRemesa
   */
  public void setRemesasIdRemesa(int remesasIdRemesa) {
        this.remesasIdRemesa = remesasIdRemesa;
    }

  /**
   *
   * @return
   */
  public int getCreditosIdCredito() {
        return this.creditosIdCredito;
    }
    
  /**
   *
   * @param creditosIdCredito
   */
  public void setCreditosIdCredito(int creditosIdCredito) {
        this.creditosIdCredito = creditosIdCredito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CreditoRemesaId) ) return false;
		 CreditoRemesaId castOther = ( CreditoRemesaId ) other; 
         
		 return (this.getRemesasIdRemesa()==castOther.getRemesasIdRemesa())
 && (this.getCreditosIdCredito()==castOther.getCreditosIdCredito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRemesasIdRemesa();
         result = 37 * result + this.getCreditosIdCredito();
         return result;
   }   


}


