package dto;
// Generated 5/06/2015 11:37:33 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name="credito"
    ,catalog="sigerbd"
)
public class Credito  implements java.io.Serializable {


     private String numeroCredito;
     private String fechaInicio;
     private String fechaFin;
     private String fechaQuebranto;
     private String fechaUltimoPago;
     private String monto;
     private String numeroCuenta;
     private String tasa;
     private String telefono;

    public Credito() {
    }

	
    public Credito(String numeroCredito) {
        this.numeroCredito = numeroCredito;
    }
    public Credito(String numeroCredito, String fechaInicio, String fechaFin, String fechaQuebranto, String fechaUltimoPago, String monto, String numeroCuenta, String tasa, String telefono) {
       this.numeroCredito = numeroCredito;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaQuebranto = fechaQuebranto;
       this.fechaUltimoPago = fechaUltimoPago;
       this.monto = monto;
       this.numeroCuenta = numeroCuenta;
       this.tasa = tasa;
       this.telefono = telefono;
    }
   
     @Id 

    
    @Column(name="numero_credito", unique=true, nullable=false, length=45)
    public String getNumeroCredito() {
        return this.numeroCredito;
    }
    
    public void setNumeroCredito(String numeroCredito) {
        this.numeroCredito = numeroCredito;
    }

    
    @Column(name="fecha_inicio", length=45)
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    
    @Column(name="fecha_fin", length=45)
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="fecha_quebranto", length=45)
    public String getFechaQuebranto() {
        return this.fechaQuebranto;
    }
    
    public void setFechaQuebranto(String fechaQuebranto) {
        this.fechaQuebranto = fechaQuebranto;
    }

    
    @Column(name="fecha_ultimo_pago", length=45)
    public String getFechaUltimoPago() {
        return this.fechaUltimoPago;
    }
    
    public void setFechaUltimoPago(String fechaUltimoPago) {
        this.fechaUltimoPago = fechaUltimoPago;
    }

    
    @Column(name="monto", length=45)
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }

    
    @Column(name="numero_cuenta", length=45)
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }

    
    @Column(name="tasa", length=45)
    public String getTasa() {
        return this.tasa;
    }
    
    public void setTasa(String tasa) {
        this.tasa = tasa;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


