package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * CreditosRemesasId generated by hbm2java
 */
public class CreditosRemesasId  implements java.io.Serializable {


     private int remesasIdRemesa;
     private int creditosIdCredito;

    public CreditosRemesasId() {
    }

    public CreditosRemesasId(int remesasIdRemesa, int creditosIdCredito) {
       this.remesasIdRemesa = remesasIdRemesa;
       this.creditosIdCredito = creditosIdCredito;
    }
   
    public int getRemesasIdRemesa() {
        return this.remesasIdRemesa;
    }
    
    public void setRemesasIdRemesa(int remesasIdRemesa) {
        this.remesasIdRemesa = remesasIdRemesa;
    }
    public int getCreditosIdCredito() {
        return this.creditosIdCredito;
    }
    
    public void setCreditosIdCredito(int creditosIdCredito) {
        this.creditosIdCredito = creditosIdCredito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CreditosRemesasId) ) return false;
		 CreditosRemesasId castOther = ( CreditosRemesasId ) other; 
         
		 return (this.getRemesasIdRemesa()==castOther.getRemesasIdRemesa())
 && (this.getCreditosIdCredito()==castOther.getCreditosIdCredito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRemesasIdRemesa();
         result = 37 * result + this.getCreditosIdCredito();
         return result;
   }   


}


