package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * CreditosRemesas generated by hbm2java
 */
public class CreditosRemesas  implements java.io.Serializable {


     private CreditosRemesasId id;
     private Creditos creditos;
     private Remesas remesas;

    public CreditosRemesas() {
    }

    public CreditosRemesas(CreditosRemesasId id, Creditos creditos, Remesas remesas) {
       this.id = id;
       this.creditos = creditos;
       this.remesas = remesas;
    }
   
    public CreditosRemesasId getId() {
        return this.id;
    }
    
    public void setId(CreditosRemesasId id) {
        this.id = id;
    }
    public Creditos getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Creditos creditos) {
        this.creditos = creditos;
    }
    public Remesas getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Remesas remesas) {
        this.remesas = remesas;
    }




}


