package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

/**
 * La clase {@code CreditoRemesa} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class CreditoRemesa implements java.io.Serializable {

    private CreditoRemesaId id;
    private Credito credito;
    private Remesa remesa;

    /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public CreditoRemesa() {
    }

    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public CreditoRemesa(CreditoRemesaId id, Credito credito, Remesa remesa) {
        this.id = id;
        this.credito = credito;
        this.remesa = remesa;
    }

    /**
     *
     *
     * @return
     */
    public CreditoRemesaId getId() {
        return this.id;
    }

    /**
     *
     *
     * @param
     */
    public void setId(CreditoRemesaId id) {
        this.id = id;
    }

    /**
     *
     *
     * @return
     */
    public Credito getCredito() {
        return this.credito;
    }

    /**
     *
     *
     * @param
     */
    public void setCredito(Credito credito) {
        this.credito = credito;
    }

    /**
     *
     *
     * @return
     */
    public Remesa getRemesa() {
        return this.remesa;
    }

    /**
     *
     *
     * @param
     */
    public void setRemesa(Remesa remesa) {
        this.remesa = remesa;
    }
}
