package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Credito generated by hbm2java
 */
public class Credito  implements java.io.Serializable {


     private String numeroCredito;
     private String fechaInicio;
     private String fechaFin;
     private String fechaQuebranto;
     private String fechaUltimoPago;
     private String monto;
     private String numeroCuenta;
     private String tasa;
     private String telefono;

    public Credito() {
    }

	
    public Credito(String numeroCredito) {
        this.numeroCredito = numeroCredito;
    }
    public Credito(String numeroCredito, String fechaInicio, String fechaFin, String fechaQuebranto, String fechaUltimoPago, String monto, String numeroCuenta, String tasa, String telefono) {
       this.numeroCredito = numeroCredito;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaQuebranto = fechaQuebranto;
       this.fechaUltimoPago = fechaUltimoPago;
       this.monto = monto;
       this.numeroCuenta = numeroCuenta;
       this.tasa = tasa;
       this.telefono = telefono;
    }
   
    public String getNumeroCredito() {
        return this.numeroCredito;
    }
    
    public void setNumeroCredito(String numeroCredito) {
        this.numeroCredito = numeroCredito;
    }
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getFechaQuebranto() {
        return this.fechaQuebranto;
    }
    
    public void setFechaQuebranto(String fechaQuebranto) {
        this.fechaQuebranto = fechaQuebranto;
    }
    public String getFechaUltimoPago() {
        return this.fechaUltimoPago;
    }
    
    public void setFechaUltimoPago(String fechaUltimoPago) {
        this.fechaUltimoPago = fechaUltimoPago;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }
    public String getTasa() {
        return this.tasa;
    }
    
    public void setTasa(String tasa) {
        this.tasa = tasa;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


