package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

/**
 * La clase {@code CreditoRemesaId} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class CreditoRemesaId implements java.io.Serializable {

    private int remesasIdRemesa;
    private int creditosIdCredito;

    /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public CreditoRemesaId() {
    }

    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public CreditoRemesaId(int remesasIdRemesa, int creditosIdCredito) {
        this.remesasIdRemesa = remesasIdRemesa;
        this.creditosIdCredito = creditosIdCredito;
    }

    /**
     *
     *
     * @return
     */
    public int getRemesasIdRemesa() {
        return this.remesasIdRemesa;
    }

    /**
     *
     *
     * @param
     */
    public void setRemesasIdRemesa(int remesasIdRemesa) {
        this.remesasIdRemesa = remesasIdRemesa;
    }

    /**
     *
     *
     * @return
     */
    public int getCreditosIdCredito() {
        return this.creditosIdCredito;
    }

    /**
     *
     *
     * @param
     */
    public void setCreditosIdCredito(int creditosIdCredito) {
        this.creditosIdCredito = creditosIdCredito;
    }

    /**
     *
     *
     * @return
     */
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CreditoRemesaId)) {
            return false;
        }
        CreditoRemesaId castOther = (CreditoRemesaId) other;

        return (this.getRemesasIdRemesa() == castOther.getRemesasIdRemesa())
                && (this.getCreditosIdCredito() == castOther.getCreditosIdCredito());
    }

    /**
     *
     *
     * @return
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRemesasIdRemesa();
        result = 37 * result + this.getCreditosIdCredito();
        return result;
    }
}
