package dto;
// Generated 20/04/2016 12:24:33 PM by Hibernate Tools 4.3.1



/**
 * DetalleVisita generated by hbm2java
 */
public class DetalleVisita  implements java.io.Serializable {


     private Integer idDetalleVisita;
     private BloqueVisitas bloqueVisitas;
     private Impresion impresion;

    public DetalleVisita() {
    }

    public DetalleVisita(BloqueVisitas bloqueVisitas, Impresion impresion) {
       this.bloqueVisitas = bloqueVisitas;
       this.impresion = impresion;
    }
   
    public Integer getIdDetalleVisita() {
        return this.idDetalleVisita;
    }
    
    public void setIdDetalleVisita(Integer idDetalleVisita) {
        this.idDetalleVisita = idDetalleVisita;
    }
    public BloqueVisitas getBloqueVisitas() {
        return this.bloqueVisitas;
    }
    
    public void setBloqueVisitas(BloqueVisitas bloqueVisitas) {
        this.bloqueVisitas = bloqueVisitas;
    }
    public Impresion getImpresion() {
        return this.impresion;
    }
    
    public void setImpresion(Impresion impresion) {
        this.impresion = impresion;
    }




}


