package dto;
// Generated 15/06/2015 12:32:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direcciones generated by hbm2java
 */
@Entity
@Table(name="direcciones"
    ,catalog="sigerbd"
)
public class Direcciones  implements java.io.Serializable {


     private Integer idDireccion;
     private Sujetos sujetos;
     private String calle;
     private String colonia;
     private String municipio;
     private String estado;
     private String codigoPostal;
     private String tipo;

    public Direcciones() {
    }

	
    public Direcciones(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public Direcciones(Sujetos sujetos, String calle, String colonia, String municipio, String estado, String codigoPostal, String tipo) {
       this.sujetos = sujetos;
       this.calle = calle;
       this.colonia = colonia;
       this.municipio = municipio;
       this.estado = estado;
       this.codigoPostal = codigoPostal;
       this.tipo = tipo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_direccion", unique=true, nullable=false)
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sujetos_id_sujeto", nullable=false)
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }

    
    @Column(name="calle", length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="colonia", length=45)
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    
    @Column(name="municipio", length=45)
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="codigo_postal", length=45)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


