package dto;
// Generated 7/08/2015 09:51:09 AM by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer idDireccion;
     private Sujeto sujeto;
     private String calle;
     private String colonia;
     private String municipio;
     private String estado;
     private String codigoPostal;
     private String tipo;

  /**
   *
   */
  public Direccion() {
    }

  /**
   *
   * @param sujeto
   * @param calle
   */
  public Direccion(Sujeto sujeto, String calle) {
        this.sujeto = sujeto;
        this.calle = calle;
    }

  /**
   *
   * @param sujeto
   * @param calle
   * @param colonia
   * @param municipio
   * @param estado
   * @param codigoPostal
   * @param tipo
   */
  public Direccion(Sujeto sujeto, String calle, String colonia, String municipio, String estado, String codigoPostal, String tipo) {
       this.sujeto = sujeto;
       this.calle = calle;
       this.colonia = colonia;
       this.municipio = municipio;
       this.estado = estado;
       this.codigoPostal = codigoPostal;
       this.tipo = tipo;
    }
   
  /**
   *
   * @return
   */
  public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
  /**
   *
   * @param idDireccion
   */
  public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }

  /**
   *
   * @return
   */
  public Sujeto getSujeto() {
        return this.sujeto;
    }
    
  /**
   *
   * @param sujeto
   */
  public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }

  /**
   *
   * @return
   */
  public String getCalle() {
        return this.calle;
    }
    
  /**
   *
   * @param calle
   */
  public void setCalle(String calle) {
        this.calle = calle;
    }

  /**
   *
   * @return
   */
  public String getColonia() {
        return this.colonia;
    }
    
  /**
   *
   * @param colonia
   */
  public void setColonia(String colonia) {
        this.colonia = colonia;
    }

  /**
   *
   * @return
   */
  public String getMunicipio() {
        return this.municipio;
    }
    
  /**
   *
   * @param municipio
   */
  public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

  /**
   *
   * @return
   */
  public String getEstado() {
        return this.estado;
    }
    
  /**
   *
   * @param estado
   */
  public void setEstado(String estado) {
        this.estado = estado;
    }

  /**
   *
   * @return
   */
  public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
  /**
   *
   * @param codigoPostal
   */
  public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

  /**
   *
   * @return
   */
  public String getTipo() {
        return this.tipo;
    }
    
  /**
   *
   * @param tipo
   */
  public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


