package dto;
// Generated 18/08/2015 11:07:25 AM by Hibernate Tools 4.3.1




/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer idDireccion;
     private Sujeto sujeto;
     private String calle;
     private String colonia;
     private String municipio;
     private String estado;
     private String codigoPostal;
     private String tipo;

    public Direccion() {
    }

	
    public Direccion(Sujeto sujeto, String calle) {
        this.sujeto = sujeto;
        this.calle = calle;
    }
    public Direccion(Sujeto sujeto, String calle, String colonia, String municipio, String estado, String codigoPostal, String tipo) {
       this.sujeto = sujeto;
       this.calle = calle;
       this.colonia = colonia;
       this.municipio = municipio;
       this.estado = estado;
       this.codigoPostal = codigoPostal;
       this.tipo = tipo;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public Sujeto getSujeto() {
        return this.sujeto;
    }
    
    public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


