package dto;
// Generated 2/12/2015 01:29:58 PM by Hibernate Tools 4.3.1



/**
 * Email generated by hbm2java
 */
public class Email  implements java.io.Serializable {


     private Integer idEmail;
     private Sujeto sujeto;
     private String direccion;
     private String tipo;

    public Email() {
    }

	
    public Email(Sujeto sujeto, String direccion) {
        this.sujeto = sujeto;
        this.direccion = direccion;
    }
    public Email(Sujeto sujeto, String direccion, String tipo) {
       this.sujeto = sujeto;
       this.direccion = direccion;
       this.tipo = tipo;
    }
   
    public Integer getIdEmail() {
        return this.idEmail;
    }
    
    public void setIdEmail(Integer idEmail) {
        this.idEmail = idEmail;
    }
    public Sujeto getSujeto() {
        return this.sujeto;
    }
    
    public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


