package dto;
// Generated 5/06/2015 11:37:33 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emails generated by hbm2java
 */
@Entity
@Table(name="emails"
    ,catalog="sigerbd"
)
public class Emails  implements java.io.Serializable {


     private Integer idEmail;
     private Sujetos sujetos;
     private String direccion;
     private String tipo;

    public Emails() {
    }

	
    public Emails(Sujetos sujetos, String direccion) {
        this.sujetos = sujetos;
        this.direccion = direccion;
    }
    public Emails(Sujetos sujetos, String direccion, String tipo) {
       this.sujetos = sujetos;
       this.direccion = direccion;
       this.tipo = tipo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_email", unique=true, nullable=false)
    public Integer getIdEmail() {
        return this.idEmail;
    }
    
    public void setIdEmail(Integer idEmail) {
        this.idEmail = idEmail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sujetos_id_sujeto", nullable=false)
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="tipo", length=15)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


