package dto;
// Generated 20/10/2016 11:15:34 AM by Hibernate Tools 4.3.1



/**
 * Email generated by hbm2java
 */
public class Email  implements java.io.Serializable {


     private Integer idEmail;
     private Sujeto sujeto;
     private String direccion;
     private String tipo;
     private int principal;

    public Email() {
    }

	
    public Email(Sujeto sujeto, String direccion, int principal) {
        this.sujeto = sujeto;
        this.direccion = direccion;
        this.principal = principal;
    }
    public Email(Sujeto sujeto, String direccion, String tipo, int principal) {
       this.sujeto = sujeto;
       this.direccion = direccion;
       this.tipo = tipo;
       this.principal = principal;
    }
   
    public Integer getIdEmail() {
        return this.idEmail;
    }
    
    public void setIdEmail(Integer idEmail) {
        this.idEmail = idEmail;
    }
    public Sujeto getSujeto() {
        return this.sujeto;
    }
    
    public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(int principal) {
        this.principal = principal;
    }




}


