package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Emails generated by hbm2java
 */
public class Emails  implements java.io.Serializable {


     private Integer idEmail;
     private Sujetos sujetos;
     private String direccion;
     private String tipo;

    public Emails() {
    }

	
    public Emails(Sujetos sujetos, String direccion) {
        this.sujetos = sujetos;
        this.direccion = direccion;
    }
    public Emails(Sujetos sujetos, String direccion, String tipo) {
       this.sujetos = sujetos;
       this.direccion = direccion;
       this.tipo = tipo;
    }
   
    public Integer getIdEmail() {
        return this.idEmail;
    }
    
    public void setIdEmail(Integer idEmail) {
        this.idEmail = idEmail;
    }
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


