package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * La clase {@code Empresa} permite ... 
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Empresa  implements java.io.Serializable {

     private Integer idEmpresa;
     private Sujeto sujeto;
     private String nombreCorto;
     private Set productos = new HashSet(0);
     private Set creditos = new HashSet(0);

     /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Empresa() {
    }
	
    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public Empresa(Sujeto sujeto, String nombreCorto) {
        this.sujeto = sujeto;
        this.nombreCorto = nombreCorto;
    }
    
    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public Empresa(Sujeto sujeto, String nombreCorto, Set productos, Set creditos) {
       this.sujeto = sujeto;
       this.nombreCorto = nombreCorto;
       this.productos = productos;
       this.creditos = creditos;
    }
   
    /**
     *
     *
     * @return
     */
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    /**
     *
     *
     * @param
     */
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    
    /**
     *
     *
     * @return
     */
    public Sujeto getSujeto() {
        return this.sujeto;
    }
    
    /**
     *
     *
     * @param
     */
    public void setSujeto(Sujeto sujeto) {
        this.sujeto = sujeto;
    }
    
    /**
     *
     *
     * @return
     */
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    /**
     *
     *
     * @param
     */
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    
    /**
     *
     *
     * @return
     */
    public Set getProductos() {
        return this.productos;
    }
    
    /**
     *
     *
     * @param
     */
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    
    /**
     *
     *
     * @return
     */
    public Set getCreditos() {
        return this.creditos;
    }
    
    /**
     *
     *
     * @param
     */
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }
}