package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private Sujetos sujetos;
     private String nombreCorto;
     private Set productoses = new HashSet(0);
     private Set creditoses = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(Sujetos sujetos, String nombreCorto) {
        this.sujetos = sujetos;
        this.nombreCorto = nombreCorto;
    }
    public Empresas(Sujetos sujetos, String nombreCorto, Set productoses, Set creditoses) {
       this.sujetos = sujetos;
       this.nombreCorto = nombreCorto;
       this.productoses = productoses;
       this.creditoses = creditoses;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
    public Set getCreditoses() {
        return this.creditoses;
    }
    
    public void setCreditoses(Set creditoses) {
        this.creditoses = creditoses;
    }




}


