package dto;
// Generated 15/06/2015 12:32:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name="empresas"
    ,catalog="sigerbd"
)
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private Sujetos sujetos;
     private String nombreCorto;
     private Set productoses = new HashSet(0);
     private Set creditoses = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(Sujetos sujetos, String nombreCorto) {
        this.sujetos = sujetos;
        this.nombreCorto = nombreCorto;
    }
    public Empresas(Sujetos sujetos, String nombreCorto, Set productoses, Set creditoses) {
       this.sujetos = sujetos;
       this.nombreCorto = nombreCorto;
       this.productoses = productoses;
       this.creditoses = creditoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_empresa", unique=true, nullable=false)
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sujetos_id_sujeto", nullable=false)
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }

    
    @Column(name="nombre_corto", nullable=false, length=30)
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresas")
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresas")
    public Set getCreditoses() {
        return this.creditoses;
    }
    
    public void setCreditoses(Set creditoses) {
        this.creditoses = creditoses;
    }




}


