package dto;
// Generated 18/08/2015 11:07:25 AM by Hibernate Tools 4.3.1



/**
 * EstadoRepublica generated by hbm2java
 */
public class EstadoRepublica  implements java.io.Serializable {


     private Integer idEstado;
     private String nombre;

    public EstadoRepublica() {
    }

    public EstadoRepublica(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


