package dto;
// Generated 25/11/2015 11:44:49 AM by Hibernate Tools 4.3.1



/**
 * EstatusInformativo generated by hbm2java
 */
public class EstatusInformativo  implements java.io.Serializable {


     private Integer idEstatusInformativo;
     private String estatus;

    public EstatusInformativo() {
    }

    public EstatusInformativo(String estatus) {
       this.estatus = estatus;
    }
   
    public Integer getIdEstatusInformativo() {
        return this.idEstatusInformativo;
    }
    
    public void setIdEstatusInformativo(Integer idEstatusInformativo) {
        this.idEstatusInformativo = idEstatusInformativo;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


