package dto;
// Generated 5/06/2015 11:37:33 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facs generated by hbm2java
 */
@Entity
@Table(name="facs"
    ,catalog="sigerbd"
)
public class Facs  implements java.io.Serializable {


     private Integer idFac;
     private Remesas remesas;
     private Integer mes;
     private Integer anio;
     private Float facPor;
     private String facMes;

    public Facs() {
    }

	
    public Facs(Remesas remesas) {
        this.remesas = remesas;
    }
    public Facs(Remesas remesas, Integer mes, Integer anio, Float facPor, String facMes) {
       this.remesas = remesas;
       this.mes = mes;
       this.anio = anio;
       this.facPor = facPor;
       this.facMes = facMes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_fac", unique=true, nullable=false)
    public Integer getIdFac() {
        return this.idFac;
    }
    
    public void setIdFac(Integer idFac) {
        this.idFac = idFac;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="remesas_id_remesa", nullable=false)
    public Remesas getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Remesas remesas) {
        this.remesas = remesas;
    }

    
    @Column(name="mes")
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="fac_por", precision=12, scale=0)
    public Float getFacPor() {
        return this.facPor;
    }
    
    public void setFacPor(Float facPor) {
        this.facPor = facPor;
    }

    
    @Column(name="fac_mes", length=100)
    public String getFacMes() {
        return this.facMes;
    }
    
    public void setFacMes(String facMes) {
        this.facMes = facMes;
    }




}


