package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Facs generated by hbm2java
 */
public class Facs  implements java.io.Serializable {


     private Integer idFac;
     private Remesas remesas;
     private Integer mes;
     private Integer anio;
     private Float facPor;
     private String facMes;

    public Facs() {
    }

	
    public Facs(Remesas remesas) {
        this.remesas = remesas;
    }
    public Facs(Remesas remesas, Integer mes, Integer anio, Float facPor, String facMes) {
       this.remesas = remesas;
       this.mes = mes;
       this.anio = anio;
       this.facPor = facPor;
       this.facMes = facMes;
    }
   
    public Integer getIdFac() {
        return this.idFac;
    }
    
    public void setIdFac(Integer idFac) {
        this.idFac = idFac;
    }
    public Remesas getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Remesas remesas) {
        this.remesas = remesas;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Float getFacPor() {
        return this.facPor;
    }
    
    public void setFacPor(Float facPor) {
        this.facPor = facPor;
    }
    public String getFacMes() {
        return this.facMes;
    }
    
    public void setFacMes(String facMes) {
        this.facMes = facMes;
    }




}


