package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gestiones generated by hbm2java
 */
public class Gestiones  implements java.io.Serializable {


     private Integer idGestion;
     private Creditos creditos;
     private Date fecha;

    public Gestiones() {
    }

	
    public Gestiones(Creditos creditos) {
        this.creditos = creditos;
    }
    public Gestiones(Creditos creditos, Date fecha) {
       this.creditos = creditos;
       this.fecha = fecha;
    }
   
    public Integer getIdGestion() {
        return this.idGestion;
    }
    
    public void setIdGestion(Integer idGestion) {
        this.idGestion = idGestion;
    }
    public Creditos getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Creditos creditos) {
        this.creditos = creditos;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


