package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gestores generated by hbm2java
 */
public class Gestores  implements java.io.Serializable {


     private Integer idGestor;
     private Usuarios usuarios;
     private String extension;
     private boolean activo;
     private Set creditoses = new HashSet(0);

    public Gestores() {
    }

	
    public Gestores(Usuarios usuarios, boolean activo) {
        this.usuarios = usuarios;
        this.activo = activo;
    }
    public Gestores(Usuarios usuarios, String extension, boolean activo, Set creditoses) {
       this.usuarios = usuarios;
       this.extension = extension;
       this.activo = activo;
       this.creditoses = creditoses;
    }
   
    public Integer getIdGestor() {
        return this.idGestor;
    }
    
    public void setIdGestor(Integer idGestor) {
        this.idGestor = idGestor;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getCreditoses() {
        return this.creditoses;
    }
    
    public void setCreditoses(Set creditoses) {
        this.creditoses = creditoses;
    }




}


