package dto;
// Generated 30/05/2016 10:43:48 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Impresion generated by hbm2java
 */
public class Impresion  implements java.io.Serializable {


     private Integer idImpresion;
     private Credito credito;
     private Direccion direccion;
     private Date fechaImpresion;
     private int tipoImpresion;
     private Set detalleVisitas = new HashSet(0);

    public Impresion() {
    }

	
    public Impresion(Credito credito, Direccion direccion, Date fechaImpresion, int tipoImpresion) {
        this.credito = credito;
        this.direccion = direccion;
        this.fechaImpresion = fechaImpresion;
        this.tipoImpresion = tipoImpresion;
    }
    public Impresion(Credito credito, Direccion direccion, Date fechaImpresion, int tipoImpresion, Set detalleVisitas) {
       this.credito = credito;
       this.direccion = direccion;
       this.fechaImpresion = fechaImpresion;
       this.tipoImpresion = tipoImpresion;
       this.detalleVisitas = detalleVisitas;
    }
   
    public Integer getIdImpresion() {
        return this.idImpresion;
    }
    
    public void setIdImpresion(Integer idImpresion) {
        this.idImpresion = idImpresion;
    }
    public Credito getCredito() {
        return this.credito;
    }
    
    public void setCredito(Credito credito) {
        this.credito = credito;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Date getFechaImpresion() {
        return this.fechaImpresion;
    }
    
    public void setFechaImpresion(Date fechaImpresion) {
        this.fechaImpresion = fechaImpresion;
    }
    public int getTipoImpresion() {
        return this.tipoImpresion;
    }
    
    public void setTipoImpresion(int tipoImpresion) {
        this.tipoImpresion = tipoImpresion;
    }
    public Set getDetalleVisitas() {
        return this.detalleVisitas;
    }
    
    public void setDetalleVisitas(Set detalleVisitas) {
        this.detalleVisitas = detalleVisitas;
    }




}


