package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Lineas generated by hbm2java
 */
public class Lineas  implements java.io.Serializable {


     private int idLinea;
     private Creditos creditos;
     private String telefono;

    public Lineas() {
    }

    public Lineas(int idLinea, Creditos creditos, String telefono) {
       this.idLinea = idLinea;
       this.creditos = creditos;
       this.telefono = telefono;
    }
   
    public int getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(int idLinea) {
        this.idLinea = idLinea;
    }
    public Creditos getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Creditos creditos) {
        this.creditos = creditos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


