package dto;
// Generated 5/06/2015 11:37:33 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lineas generated by hbm2java
 */
@Entity
@Table(name="lineas"
    ,catalog="sigerbd"
)
public class Lineas  implements java.io.Serializable {


     private int idLinea;
     private Creditos creditos;
     private String telefono;

    public Lineas() {
    }

    public Lineas(int idLinea, Creditos creditos, String telefono) {
       this.idLinea = idLinea;
       this.creditos = creditos;
       this.telefono = telefono;
    }
   
     @Id 

    
    @Column(name="id_linea", unique=true, nullable=false)
    public int getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(int idLinea) {
        this.idLinea = idLinea;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creditos_id_credito", nullable=false)
    public Creditos getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Creditos creditos) {
        this.creditos = creditos;
    }

    
    @Column(name="telefono", nullable=false, length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


