package dto;
// Generated 25/02/2016 03:00:35 PM by Hibernate Tools 4.3.1



/**
 * MotivoDevolucion generated by hbm2java
 */
public class MotivoDevolucion  implements java.io.Serializable {


     private Integer idMotivoDevolucion;
     private ConceptoDevolucion conceptoDevolucion;
     private String motivo;
     private String descripcion;

    public MotivoDevolucion() {
    }

    public MotivoDevolucion(ConceptoDevolucion conceptoDevolucion, String motivo, String descripcion) {
       this.conceptoDevolucion = conceptoDevolucion;
       this.motivo = motivo;
       this.descripcion = descripcion;
    }
   
    public Integer getIdMotivoDevolucion() {
        return this.idMotivoDevolucion;
    }
    
    public void setIdMotivoDevolucion(Integer idMotivoDevolucion) {
        this.idMotivoDevolucion = idMotivoDevolucion;
    }
    public ConceptoDevolucion getConceptoDevolucion() {
        return this.conceptoDevolucion;
    }
    
    public void setConceptoDevolucion(ConceptoDevolucion conceptoDevolucion) {
        this.conceptoDevolucion = conceptoDevolucion;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


