package dto;
// Generated 18/08/2015 11:07:25 AM by Hibernate Tools 4.3.1



/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private int idEstadoEstados;
     private String nombre;

    public Municipio() {
    }

    public Municipio(int idEstadoEstados, String nombre) {
       this.idEstadoEstados = idEstadoEstados;
       this.nombre = nombre;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public int getIdEstadoEstados() {
        return this.idEstadoEstados;
    }
    
    public void setIdEstadoEstados(int idEstadoEstados) {
        this.idEstadoEstados = idEstadoEstados;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


