package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Empresas empresas;
     private String nombre;
     private String descripcion;
     private Set creditoses = new HashSet(0);
     private Set subproductoses = new HashSet(0);

    public Productos() {
    }

	
    public Productos(Empresas empresas, String nombre) {
        this.empresas = empresas;
        this.nombre = nombre;
    }
    public Productos(Empresas empresas, String nombre, String descripcion, Set creditoses, Set subproductoses) {
       this.empresas = empresas;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.creditoses = creditoses;
       this.subproductoses = subproductoses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCreditoses() {
        return this.creditoses;
    }
    
    public void setCreditoses(Set creditoses) {
        this.creditoses = creditoses;
    }
    public Set getSubproductoses() {
        return this.subproductoses;
    }
    
    public void setSubproductoses(Set subproductoses) {
        this.subproductoses = subproductoses;
    }




}


