package dto;
// Generated 20/10/2016 11:15:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Institucion institucion;
     private String nombre;
     private String familia;
     private String descripcion;
     private Set creditos = new HashSet(0);
     private Set subproductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Institucion institucion, String nombre, String familia) {
        this.institucion = institucion;
        this.nombre = nombre;
        this.familia = familia;
    }
    public Producto(Institucion institucion, String nombre, String familia, String descripcion, Set creditos, Set subproductos) {
       this.institucion = institucion;
       this.nombre = nombre;
       this.familia = familia;
       this.descripcion = descripcion;
       this.creditos = creditos;
       this.subproductos = subproductos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Institucion getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(Institucion institucion) {
        this.institucion = institucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(String familia) {
        this.familia = familia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }
    public Set getSubproductos() {
        return this.subproductos;
    }
    
    public void setSubproductos(Set subproductos) {
        this.subproductos = subproductos;
    }




}


