package dto;
// Generated 2/12/2015 01:29:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PromesaPago generated by hbm2java
 */
public class PromesaPago  implements java.io.Serializable {


     private int idPromesaPago;
     private ConvenioPago convenioPago;
     private Date fecha;
     private float montoAcordado;
     private Set pagos = new HashSet(0);

    public PromesaPago() {
    }

	
    public PromesaPago(int idPromesaPago, ConvenioPago convenioPago, Date fecha, float montoAcordado) {
        this.idPromesaPago = idPromesaPago;
        this.convenioPago = convenioPago;
        this.fecha = fecha;
        this.montoAcordado = montoAcordado;
    }
    public PromesaPago(int idPromesaPago, ConvenioPago convenioPago, Date fecha, float montoAcordado, Set pagos) {
       this.idPromesaPago = idPromesaPago;
       this.convenioPago = convenioPago;
       this.fecha = fecha;
       this.montoAcordado = montoAcordado;
       this.pagos = pagos;
    }
   
    public int getIdPromesaPago() {
        return this.idPromesaPago;
    }
    
    public void setIdPromesaPago(int idPromesaPago) {
        this.idPromesaPago = idPromesaPago;
    }
    public ConvenioPago getConvenioPago() {
        return this.convenioPago;
    }
    
    public void setConvenioPago(ConvenioPago convenioPago) {
        this.convenioPago = convenioPago;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public float getMontoAcordado() {
        return this.montoAcordado;
    }
    
    public void setMontoAcordado(float montoAcordado) {
        this.montoAcordado = montoAcordado;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


