package dto;
// Generated 20/10/2016 11:15:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * QuienGestion generated by hbm2java
 */
public class QuienGestion  implements java.io.Serializable {


     private Integer idQuienGestion;
     private TipoQuienGestion tipoQuienGestion;
     private String quien;
     private Set gestions = new HashSet(0);

    public QuienGestion() {
    }

	
    public QuienGestion(TipoQuienGestion tipoQuienGestion, String quien) {
        this.tipoQuienGestion = tipoQuienGestion;
        this.quien = quien;
    }
    public QuienGestion(TipoQuienGestion tipoQuienGestion, String quien, Set gestions) {
       this.tipoQuienGestion = tipoQuienGestion;
       this.quien = quien;
       this.gestions = gestions;
    }
   
    public Integer getIdQuienGestion() {
        return this.idQuienGestion;
    }
    
    public void setIdQuienGestion(Integer idQuienGestion) {
        this.idQuienGestion = idQuienGestion;
    }
    public TipoQuienGestion getTipoQuienGestion() {
        return this.tipoQuienGestion;
    }
    
    public void setTipoQuienGestion(TipoQuienGestion tipoQuienGestion) {
        this.tipoQuienGestion = tipoQuienGestion;
    }
    public String getQuien() {
        return this.quien;
    }
    
    public void setQuien(String quien) {
        this.quien = quien;
    }
    public Set getGestions() {
        return this.gestions;
    }
    
    public void setGestions(Set gestions) {
        this.gestions = gestions;
    }




}


