package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * La clase {@code Remesa} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Remesa implements java.io.Serializable {

    private Integer idRemesa;
    private Integer mesesVencidos;
    private Float saldoVencido;
    private String estatus;
    private Date fechaUltimoPago;
    private Set facs = new HashSet(0);
    private Set creditoRemesas = new HashSet(0);

    /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Remesa() {
    }

    /**
     * Constructor parametrizado <br/>
     * Configura ...
     */
    public Remesa(Integer mesesVencidos, Float saldoVencido, String estatus, Date fechaUltimoPago, Set facs, Set creditoRemesas) {
        this.mesesVencidos = mesesVencidos;
        this.saldoVencido = saldoVencido;
        this.estatus = estatus;
        this.fechaUltimoPago = fechaUltimoPago;
        this.facs = facs;
        this.creditoRemesas = creditoRemesas;
    }

    /**
     *
     *
     * @return
     */
    public Integer getIdRemesa() {
        return this.idRemesa;
    }

    /**
     *
     *
     * @param
     */
    public void setIdRemesa(Integer idRemesa) {
        this.idRemesa = idRemesa;
    }

    /**
     *
     *
     * @return
     */
    public Integer getMesesVencidos() {
        return this.mesesVencidos;
    }

    /**
     *
     *
     * @param
     */
    public void setMesesVencidos(Integer mesesVencidos) {
        this.mesesVencidos = mesesVencidos;
    }

    /**
     *
     *
     * @return
     */
    public Float getSaldoVencido() {
        return this.saldoVencido;
    }

    /**
     *
     *
     * @param
     */
    public void setSaldoVencido(Float saldoVencido) {
        this.saldoVencido = saldoVencido;
    }

    /**
     *
     *
     * @return
     */
    public String getEstatus() {
        return this.estatus;
    }

    /**
     *
     *
     * @param
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    /**
     *
     *
     * @return
     */
    public Date getFechaUltimoPago() {
        return this.fechaUltimoPago;
    }

    /**
     *
     *
     * @param
     */
    public void setFechaUltimoPago(Date fechaUltimoPago) {
        this.fechaUltimoPago = fechaUltimoPago;
    }

    /**
     *
     *
     * @return
     */
    public Set getFacs() {
        return this.facs;
    }

    /**
     *
     *
     * @param
     */
    public void setFacs(Set facs) {
        this.facs = facs;
    }

    /**
     *
     *
     * @return
     */
    public Set getCreditoRemesas() {
        return this.creditoRemesas;
    }

    /**
     *
     *
     * @param
     */
    public void setCreditoRemesas(Set creditoRemesas) {
        this.creditoRemesas = creditoRemesas;
    }
}