package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * La clase {@code Subproducto} permite ... 
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Subproducto  implements java.io.Serializable {

     private Integer idSubproducto;
     private Producto producto;
     private String nombre;
     private String descripcion;
     private Set creditos = new HashSet(0);

         /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Subproducto() {
    }
	
        /**
     * Constructor  parametrizado. <br/>
     * Configura ...
     */
    public Subproducto(Producto producto, String nombre) {
        this.producto = producto;
        this.nombre = nombre;
    }
        /**
     * Constructor parametrizado. <br/>
     * Configura ...
     */
    public Subproducto(Producto producto, String nombre, String descripcion, Set creditos) {
       this.producto = producto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.creditos = creditos;
    }
   
    /**
     *
     *
     * @return
     */
    public Integer getIdSubproducto() {
        return this.idSubproducto;
    }
    
    /**
     *
     *
     * @param
     */
    public void setIdSubproducto(Integer idSubproducto) {
        this.idSubproducto = idSubproducto;
    }
    
    /**
     *
     *
     * @return
     */
    public Producto getProducto() {
        return this.producto;
    }
    
    /**
     *
     *
     * @param
     */
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    
    /**
     *
     *
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }
    
    /**
     *
     *
     * @param
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    /**
     *
     *
     * @return
     */
    public String getDescripcion() {
        return this.descripcion;
    }
    
    /**
     *
     *
     * @param
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    /**
     *
     *
     * @return
     */
    public Set getCreditos() {
        return this.creditos;
    }
    
    /**
     *
     *
     * @param
     */
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }
}