package dto;
// Generated 5/06/2015 11:37:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subproductos generated by hbm2java
 */
@Entity
@Table(name="subproductos"
    ,catalog="sigerbd"
)
public class Subproductos  implements java.io.Serializable {


     private Integer idSubproducto;
     private Productos productos;
     private String nombre;
     private String descripcion;
     private Set creditoses = new HashSet(0);

    public Subproductos() {
    }

	
    public Subproductos(Productos productos, String nombre) {
        this.productos = productos;
        this.nombre = nombre;
    }
    public Subproductos(Productos productos, String nombre, String descripcion, Set creditoses) {
       this.productos = productos;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.creditoses = creditoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_subproducto", unique=true, nullable=false)
    public Integer getIdSubproducto() {
        return this.idSubproducto;
    }
    
    public void setIdSubproducto(Integer idSubproducto) {
        this.idSubproducto = idSubproducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productos_id_producto", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subproductos")
    public Set getCreditoses() {
        return this.creditoses;
    }
    
    public void setCreditoses(Set creditoses) {
        this.creditoses = creditoses;
    }




}


