package dto;
// Generated 7/08/2015 09:51:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subproducto generated by hbm2java
 */
public class Subproducto  implements java.io.Serializable {


     private Integer idSubproducto;
     private Producto producto;
     private String nombre;
     private String descripcion;
     private Set creditos = new HashSet(0);

  /**
   *
   */
  public Subproducto() {
    }

  /**
   *
   * @param producto
   * @param nombre
   */
  public Subproducto(Producto producto, String nombre) {
        this.producto = producto;
        this.nombre = nombre;
    }

  /**
   *
   * @param producto
   * @param nombre
   * @param descripcion
   * @param creditos
   */
  public Subproducto(Producto producto, String nombre, String descripcion, Set creditos) {
       this.producto = producto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.creditos = creditos;
    }
   
  /**
   *
   * @return
   */
  public Integer getIdSubproducto() {
        return this.idSubproducto;
    }
    
  /**
   *
   * @param idSubproducto
   */
  public void setIdSubproducto(Integer idSubproducto) {
        this.idSubproducto = idSubproducto;
    }

  /**
   *
   * @return
   */
  public Producto getProducto() {
        return this.producto;
    }
    
  /**
   *
   * @param producto
   */
  public void setProducto(Producto producto) {
        this.producto = producto;
    }

  /**
   *
   * @return
   */
  public String getNombre() {
        return this.nombre;
    }
    
  /**
   *
   * @param nombre
   */
  public void setNombre(String nombre) {
        this.nombre = nombre;
    }

  /**
   *
   * @return
   */
  public String getDescripcion() {
        return this.descripcion;
    }
    
  /**
   *
   * @param descripcion
   */
  public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

  /**
   *
   * @return
   */
  public Set getCreditos() {
        return this.creditos;
    }
    
  /**
   *
   * @param creditos
   */
  public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }




}


