package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * La clase {@code Sujeto} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Sujeto implements java.io.Serializable {

    private Integer idSujeto;
    private String nombreRazonSocial;
    private String rfc;
    private int eliminado;
    private Set direccions = new HashSet(0);
    private Set emails = new HashSet(0);
    private Set empresas = new HashSet(0);
    private Set clientes = new HashSet(0);
    private Set telefonos = new HashSet(0);
    private Set contactos = new HashSet(0);

        /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Sujeto() {
    }

        /**
     * Constructor parametrizado. <br/>
     * Configura ...
     */
    public Sujeto(String nombreRazonSocial, int eliminado) {
        this.nombreRazonSocial = nombreRazonSocial;
        this.eliminado = eliminado;
    }

        /**
     * Constructor parametrizado. <br/>
     * Configura ...
     */
    public Sujeto(String nombreRazonSocial, String rfc, int eliminado, Set direccions, Set emails, Set empresas, Set clientes, Set telefonos, Set contactos) {
        this.nombreRazonSocial = nombreRazonSocial;
        this.rfc = rfc;
        this.eliminado = eliminado;
        this.direccions = direccions;
        this.emails = emails;
        this.empresas = empresas;
        this.clientes = clientes;
        this.telefonos = telefonos;
        this.contactos = contactos;
    }

    /**
     *
     *
     * @return
     */
    public Integer getIdSujeto() {
        return this.idSujeto;
    }

    /**
     *
     *
     * @param
     */
    public void setIdSujeto(Integer idSujeto) {
        this.idSujeto = idSujeto;
    }

    /**
     *
     *
     * @return
     */
    public String getNombreRazonSocial() {
        return this.nombreRazonSocial;
    }

    /**
     *
     *
     * @param
     */
    public void setNombreRazonSocial(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }

    /**
     *
     *
     * @return
     */
    public String getRfc() {
        return this.rfc;
    }

    /**
     *
     *
     * @param
     */
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    /**
     *
     *
     * @return
     */
    public int getEliminado() {
        return this.eliminado;
    }

    /**
     *
     *
     * @param
     */
    public void setEliminado(int eliminado) {
        this.eliminado = eliminado;
    }

    /**
     *
     *
     * @return
     */
    public Set getDireccions() {
        return this.direccions;
    }

    /**
     *
     *
     * @param
     */
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }

    /**
     *
     *
     * @return
     */
    public Set getEmails() {
        return this.emails;
    }

    /**
     *
     *
     * @param
     */
    public void setEmails(Set emails) {
        this.emails = emails;
    }

    /**
     *
     *
     * @return
     */
    public Set getEmpresas() {
        return this.empresas;
    }

    /**
     *
     *
     * @param
     */
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }

    /**
     *
     *
     * @return
     */
    public Set getClientes() {
        return this.clientes;
    }

    /**
     *
     *
     * @param
     */
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

    /**
     *
     *
     * @return
     */
    public Set getTelefonos() {
        return this.telefonos;
    }

    /**
     *
     *
     * @param
     */
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }

    /**
     *
     *
     * @return
     */
    public Set getContactos() {
        return this.contactos;
    }

    /**
     *
     *
     * @param
     */
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }
}
