package dto;
// Generated 22/03/2016 03:28:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sujeto generated by hbm2java
 */
public class Sujeto  implements java.io.Serializable {


     private Integer idSujeto;
     private String nombreRazonSocial;
     private String rfc;
     private int eliminado;
     private Set telefonos = new HashSet(0);
     private Set contactos = new HashSet(0);
     private Set direccions = new HashSet(0);
     private Set institucions = new HashSet(0);
     private Set despachos = new HashSet(0);
     private Set deudors = new HashSet(0);
     private Set emails = new HashSet(0);

    public Sujeto() {
    }

	
    public Sujeto(String nombreRazonSocial, int eliminado) {
        this.nombreRazonSocial = nombreRazonSocial;
        this.eliminado = eliminado;
    }
    public Sujeto(String nombreRazonSocial, String rfc, int eliminado, Set telefonos, Set contactos, Set direccions, Set institucions, Set despachos, Set deudors, Set emails) {
       this.nombreRazonSocial = nombreRazonSocial;
       this.rfc = rfc;
       this.eliminado = eliminado;
       this.telefonos = telefonos;
       this.contactos = contactos;
       this.direccions = direccions;
       this.institucions = institucions;
       this.despachos = despachos;
       this.deudors = deudors;
       this.emails = emails;
    }
   
    public Integer getIdSujeto() {
        return this.idSujeto;
    }
    
    public void setIdSujeto(Integer idSujeto) {
        this.idSujeto = idSujeto;
    }
    public String getNombreRazonSocial() {
        return this.nombreRazonSocial;
    }
    
    public void setNombreRazonSocial(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public int getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(int eliminado) {
        this.eliminado = eliminado;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }
    public Set getInstitucions() {
        return this.institucions;
    }
    
    public void setInstitucions(Set institucions) {
        this.institucions = institucions;
    }
    public Set getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set despachos) {
        this.despachos = despachos;
    }
    public Set getDeudors() {
        return this.deudors;
    }
    
    public void setDeudors(Set deudors) {
        this.deudors = deudors;
    }
    public Set getEmails() {
        return this.emails;
    }
    
    public void setEmails(Set emails) {
        this.emails = emails;
    }




}


