package dto;
// Generated 5/06/2015 11:37:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sujetos generated by hbm2java
 */
@Entity
@Table(name="sujetos"
    ,catalog="sigerbd"
)
public class Sujetos  implements java.io.Serializable {


     private Integer idSujeto;
     private String nombreRazonSocial;
     private String rfc;
     private Set direccioneses = new HashSet(0);
     private Set emailses = new HashSet(0);
     private Set empresases = new HashSet(0);
     private Set clienteses = new HashSet(0);
     private Set telefonoses = new HashSet(0);
     private Set contactoses = new HashSet(0);

    public Sujetos() {
    }

	
    public Sujetos(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }
    public Sujetos(String nombreRazonSocial, String rfc, Set direccioneses, Set emailses, Set empresases, Set clienteses, Set telefonoses, Set contactoses) {
       this.nombreRazonSocial = nombreRazonSocial;
       this.rfc = rfc;
       this.direccioneses = direccioneses;
       this.emailses = emailses;
       this.empresases = empresases;
       this.clienteses = clienteses;
       this.telefonoses = telefonoses;
       this.contactoses = contactoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sujeto", unique=true, nullable=false)
    public Integer getIdSujeto() {
        return this.idSujeto;
    }
    
    public void setIdSujeto(Integer idSujeto) {
        this.idSujeto = idSujeto;
    }

    
    @Column(name="nombre_razon_social", nullable=false, length=100)
    public String getNombreRazonSocial() {
        return this.nombreRazonSocial;
    }
    
    public void setNombreRazonSocial(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }

    
    @Column(name="rfc", length=15)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sujetos")
    public Set getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(Set direccioneses) {
        this.direccioneses = direccioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sujetos")
    public Set getEmailses() {
        return this.emailses;
    }
    
    public void setEmailses(Set emailses) {
        this.emailses = emailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sujetos")
    public Set getEmpresases() {
        return this.empresases;
    }
    
    public void setEmpresases(Set empresases) {
        this.empresases = empresases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sujetos")
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sujetos")
    public Set getTelefonoses() {
        return this.telefonoses;
    }
    
    public void setTelefonoses(Set telefonoses) {
        this.telefonoses = telefonoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sujetos")
    public Set getContactoses() {
        return this.contactoses;
    }
    
    public void setContactoses(Set contactoses) {
        this.contactoses = contactoses;
    }




}


