package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sujetos generated by hbm2java
 */
public class Sujetos  implements java.io.Serializable {


     private Integer idSujeto;
     private String nombreRazonSocial;
     private String rfc;
     private Set direccioneses = new HashSet(0);
     private Set emailses = new HashSet(0);
     private Set empresases = new HashSet(0);
     private Set clienteses = new HashSet(0);
     private Set telefonoses = new HashSet(0);
     private Set contactoses = new HashSet(0);

    public Sujetos() {
    }

	
    public Sujetos(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }
    public Sujetos(String nombreRazonSocial, String rfc, Set direccioneses, Set emailses, Set empresases, Set clienteses, Set telefonoses, Set contactoses) {
       this.nombreRazonSocial = nombreRazonSocial;
       this.rfc = rfc;
       this.direccioneses = direccioneses;
       this.emailses = emailses;
       this.empresases = empresases;
       this.clienteses = clienteses;
       this.telefonoses = telefonoses;
       this.contactoses = contactoses;
    }
   
    public Integer getIdSujeto() {
        return this.idSujeto;
    }
    
    public void setIdSujeto(Integer idSujeto) {
        this.idSujeto = idSujeto;
    }
    public String getNombreRazonSocial() {
        return this.nombreRazonSocial;
    }
    
    public void setNombreRazonSocial(String nombreRazonSocial) {
        this.nombreRazonSocial = nombreRazonSocial;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Set getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(Set direccioneses) {
        this.direccioneses = direccioneses;
    }
    public Set getEmailses() {
        return this.emailses;
    }
    
    public void setEmailses(Set emailses) {
        this.emailses = emailses;
    }
    public Set getEmpresases() {
        return this.empresases;
    }
    
    public void setEmpresases(Set empresases) {
        this.empresases = empresases;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }
    public Set getTelefonoses() {
        return this.telefonoses;
    }
    
    public void setTelefonoses(Set telefonoses) {
        this.telefonoses = telefonoses;
    }
    public Set getContactoses() {
        return this.contactoses;
    }
    
    public void setContactoses(Set contactoses) {
        this.contactoses = contactoses;
    }




}


