package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1



/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private Integer idTelefono;
     private Sujetos sujetos;
     private String numero;
     private String tipo;
     private String extension;
     private String lada;
     private String horario;

    public Telefonos() {
    }

	
    public Telefonos(Sujetos sujetos, String numero) {
        this.sujetos = sujetos;
        this.numero = numero;
    }
    public Telefonos(Sujetos sujetos, String numero, String tipo, String extension, String lada, String horario) {
       this.sujetos = sujetos;
       this.numero = numero;
       this.tipo = tipo;
       this.extension = extension;
       this.lada = lada;
       this.horario = horario;
    }
   
    public Integer getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(Integer idTelefono) {
        this.idTelefono = idTelefono;
    }
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public String getLada() {
        return this.lada;
    }
    
    public void setLada(String lada) {
        this.lada = lada;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }




}


