package dto;
// Generated 15/06/2015 12:32:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefonos generated by hbm2java
 */
@Entity
@Table(name="telefonos"
    ,catalog="sigerbd"
)
public class Telefonos  implements java.io.Serializable {


     private Integer idTelefono;
     private Sujetos sujetos;
     private String numero;
     private String tipo;
     private String extension;
     private String lada;
     private String horario;

    public Telefonos() {
    }

	
    public Telefonos(Sujetos sujetos, String numero) {
        this.sujetos = sujetos;
        this.numero = numero;
    }
    public Telefonos(Sujetos sujetos, String numero, String tipo, String extension, String lada, String horario) {
       this.sujetos = sujetos;
       this.numero = numero;
       this.tipo = tipo;
       this.extension = extension;
       this.lada = lada;
       this.horario = horario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_telefono", unique=true, nullable=false)
    public Integer getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(Integer idTelefono) {
        this.idTelefono = idTelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sujetos_id_sujeto", nullable=false)
    public Sujetos getSujetos() {
        return this.sujetos;
    }
    
    public void setSujetos(Sujetos sujetos) {
        this.sujetos = sujetos;
    }

    
    @Column(name="numero", nullable=false, length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="tipo", length=15)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="extension", length=30)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="lada", length=5)
    public String getLada() {
        return this.lada;
    }
    
    public void setLada(String lada) {
        this.lada = lada;
    }

    
    @Column(name="horario", length=45)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }




}


