package dto;
// Generated 27/07/2015 11:04:14 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * La clase {@code Usuario} permite ...
 *
 * @author
 * @author
 * @author generated by hbm2java
 * @since SigerWeb2.0
 */
public class Usuario implements java.io.Serializable {

    private Integer idUsuario;
    private String nombre;
    private String paterno;
    private String materno;
    private String nombreLogin;
    private String password;
    private int perfil;
    private String correo;
    private String imagenPerfil;
    private Set administrativos = new HashSet(0);
    private Set gestors = new HashSet(0);

    /**
     * Constructor por defecto. <br/>
     * Configura ...
     */
    public Usuario() {
    }

    /**
     * Constructor parametrizado. <br/>
     * Configura ...
     */
    public Usuario(String nombre, String paterno, String nombreLogin, String password, int perfil, String correo) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.nombreLogin = nombreLogin;
        this.password = password;
        this.perfil = perfil;
        this.correo = correo;
    }

    /**
     * Constructor parametrizado. <br/>
     * Configura ...
     */
    public Usuario(String nombre, String paterno, String materno, String nombreLogin, String password, int perfil, String correo, String imagenPerfil, Set administrativos, Set gestors) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.nombreLogin = nombreLogin;
        this.password = password;
        this.perfil = perfil;
        this.correo = correo;
        this.imagenPerfil = imagenPerfil;
        this.administrativos = administrativos;
        this.gestors = gestors;
    }

    /**
     *
     *
     * @return
     */
    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    /**
     *
     *
     * @param
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     *
     *
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     *
     *
     * @param
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     *
     *
     * @return
     */
    public String getPaterno() {
        return this.paterno;
    }

    /**
     *
     *
     * @param
     */
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }

    /**
     *
     *
     * @return
     */
    public String getMaterno() {
        return this.materno;
    }

    /**
     *
     *
     * @param
     */
    public void setMaterno(String materno) {
        this.materno = materno;
    }

    /**
     *
     *
     * @return
     */
    public String getNombreLogin() {
        return this.nombreLogin;
    }

    /**
     *
     *
     * @param
     */
    public void setNombreLogin(String nombreLogin) {
        this.nombreLogin = nombreLogin;
    }

    /**
     *
     *
     * @return
     */
    public String getPassword() {
        return this.password;
    }

    /**
     *
     *
     * @param
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     *
     * @return
     */
    public int getPerfil() {
        return this.perfil;
    }

    /**
     *
     *
     * @param
     */
    public void setPerfil(int perfil) {
        this.perfil = perfil;
    }

    /**
     *
     *
     * @return
     */
    public String getCorreo() {
        return this.correo;
    }

    /**
     *
     *
     * @param
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /**
     *
     *
     * @return
     */
    public String getImagenPerfil() {
        return this.imagenPerfil;
    }

    /**
     *
     *
     * @param
     */
    public void setImagenPerfil(String imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }

    /**
     *
     *
     * @return
     */
    public Set getAdministrativos() {
        return this.administrativos;
    }

    /**
     *
     *
     * @param
     */
    public void setAdministrativos(Set administrativos) {
        this.administrativos = administrativos;
    }

    /**
     *
     *
     * @return
     */
    public Set getGestors() {
        return this.gestors;
    }

    /**
     *
     *
     * @param
     */
    public void setGestors(Set gestors) {
        this.gestors = gestors;
    }
}
