package dto;
// Generated 15/06/2015 12:32:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="sigerbd"
)
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String paterno;
     private String materno;
     private String nombreLogin;
     private String password;
     private int perfil;
     private String correo;
     private String imagenPerfil;
     private Set administrativoses = new HashSet(0);
     private Set gestoreses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String nombre, String nombreLogin, String password, int perfil, String correo) {
        this.nombre = nombre;
        this.nombreLogin = nombreLogin;
        this.password = password;
        this.perfil = perfil;
        this.correo = correo;
    }
    public Usuarios(String nombre, String paterno, String materno, String nombreLogin, String password, int perfil, String correo, String imagenPerfil, Set administrativoses, Set gestoreses) {
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.nombreLogin = nombreLogin;
       this.password = password;
       this.perfil = perfil;
       this.correo = correo;
       this.imagenPerfil = imagenPerfil;
       this.administrativoses = administrativoses;
       this.gestoreses = gestoreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="paterno", length=45)
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }

    
    @Column(name="materno", length=45)
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }

    
    @Column(name="nombre_login", nullable=false, length=20)
    public String getNombreLogin() {
        return this.nombreLogin;
    }
    
    public void setNombreLogin(String nombreLogin) {
        this.nombreLogin = nombreLogin;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="perfil", nullable=false)
    public int getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(int perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="correo", nullable=false, length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="imagen_perfil", length=30)
    public String getImagenPerfil() {
        return this.imagenPerfil;
    }
    
    public void setImagenPerfil(String imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getAdministrativoses() {
        return this.administrativoses;
    }
    
    public void setAdministrativoses(Set administrativoses) {
        this.administrativoses = administrativoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getGestoreses() {
        return this.gestoreses;
    }
    
    public void setGestoreses(Set gestoreses) {
        this.gestoreses = gestoreses;
    }




}


