package dto;
// Generated 12/05/2015 01:10:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by cofradia team hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String paterno;
     private String materno;
     private String nombreLogin;
     private String password;
     private int perfil;
     private Set administrativoses = new HashSet(0);
     private Set gestoreses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String nombre, String nombreLogin, String password, int perfil) {
        this.nombre = nombre;
        this.nombreLogin = nombreLogin;
        this.password = password;
        this.perfil = perfil;
    }
    public Usuarios(String nombre, String paterno, String materno, String nombreLogin, String password, int perfil, Set administrativoses, Set gestoreses) {
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.nombreLogin = nombreLogin;
       this.password = password;
       this.perfil = perfil;
       this.administrativoses = administrativoses;
       this.gestoreses = gestoreses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getNombreLogin() {
        return this.nombreLogin;
    }
    
    public void setNombreLogin(String nombreLogin) {
        this.nombreLogin = nombreLogin;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(int perfil) {
        this.perfil = perfil;
    }
    public Set getAdministrativoses() {
        return this.administrativoses;
    }
    
    public void setAdministrativoses(Set administrativoses) {
        this.administrativoses = administrativoses;
    }
    public Set getGestoreses() {
        return this.gestoreses;
    }
    
    public void setGestoreses(Set gestoreses) {
        this.gestoreses = gestoreses;
    }




}


